name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node LTS 22
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build Angular project
      - name: Build Angular
        run: ng build jotto --configuration production --base-href /jotto/

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v6
        with:
          branch: gh-pages # branch to deploy to
          folder: dist/jotto # folder containing static files
          clean: true # optional: remove old files
